### ISSUE TITLE
wrap output of arithmetic operation and overflow bit into data structure

### ISSUE THREAD

**Issue by guyvdbroeck** [Juice-jl/Dice.jl#10]
Rather than returning a pair of values, it would be better to fold all the "overflow/underflow/division by 0" safety bits into their own data type.
For example, there can be `DistUInt{W}` which is an unsigned integer `W` bits wide. When you overflow or underflow, nothing happens.
There can also be a `SafeDistUInt{W}` which is a struct containing a `DistUInt{W}` and a `DistBool` represening arithmetic error.
We can implement most arithmetic operations as handling `SafeDistUInt{W}`, but now a single value is returned and you can sum two `SafeDistUInt{W}`, etc. (a monad?).
And `DistUInt{W}` can be implemented as offloading to `SafeDistUInt{W}` while throwing away the extra `DistBool`.

Concretely, I would like to be able to write:
```julia
x = uniform(SafeDistUInt{32}, 16)
y = uniform(SafeDistUInt{32}, 16)
z = uniform(SafeDistUInt{32}, 16)
x + 2*y + 3*z
```
without the need to unpack the overflow bits of the summation/multiplication. I want the resulting `SafeDistUInt{32}` to tell me if any arithmetic error happened along the way.

I also want to be able to write
```julia
x = uniform(DistUInt{32}, 16)
y = uniform(DistUInt{32}, 16)
z = uniform(DistUInt{32}, 16)
x + 2*y + 3*z
```
which means that I am confident that overflow cannot occur and I don't care to keep track of that `DistBool`.

**Comment by rtjoa** [comment]
How would we track error if `SafeDistUInt{32}` is not the program result, but affects results downstream? For example:
```julia
x = uniform(SafeDistUInt{32}, 16)
y = uniform(SafeDistUInt{32}, 16)
if some_computation(x, y)
  return flip(0.7)
else
  return flip(0.2)
end
```
Maybe...
1. We add error bits to all other types so errors can propagate to the returned value
2. We have a single program error bit that informs us whether error could have occurred anywhere

Also, if we cannot "prune width if unsat," could it still be feasible to have automatically-growing DistInts?

**Comment by guyvdbroeck** [comment]
Yeah it might be better to have an error handler in the manager where we can register an error message with some `DistBool` probability and then we can ignore it or we can ask to print all non-zero-probability errors...

**Comment by rtjoa** [comment]
I tried [adding an error bit to the manager](https://github.com/rtjoa/Dice.jl/commit/67e90b0e941a7b99d089340adafad382e6a88c33), and realized that (at least in my implementation) it can cause some false positives, such as in the following program:
```julia
# uniform on {0, 1, 2, 3}
a = DistInt([flip(0.5), flip(0.5)])
if !prob_equals(a, 3)
    a + 1
else
    a
end
```
Even though it correctly inferred that the distribution was `[0, 0.25, 0.25, 0.5]`, it reported error to be `0.25` as probabilistically-executing control flow is always evaluated by Julia.

I also toyed with [including error bits in Dist structs](https://github.com/rtjoa/Dice.jl/commit/6a22b61b8d88cdf5b0adf37eaacb7d779aeb3f49) and the behavior seems to be more predictable. If we continue down this path, I could see us having the following composition structure:
* `UnsafeDistBool`, `UnsafeDistInt`, `UnsafeDistString` do not have error bits, but all operations that on them that may fail also return an error bit that the user can decide to propagate or discard.
* `DistBool`, `DistInt`, `DistString` wrap the above, automatically propagating error bits as appropriate.

**Comment by guyvdbroeck** [comment]
this issue is now obsolete, we have an error handling dynamo
