### ISSUE TITLE
Bug in `ifelse`

### ISSUE THREAD

**Issue by PoorvaGarg** [Juice-jl/Dice.jl#64]
The following code throws a `ProbException`
```
x = DistUInt{4}(3)
y = DistUInt{4}(4)
p = pr(@dice Dice.ifelse(flip(1), y - x, x - y))
```

**Comment by guyvdbroeck** [comment]
`pr(@dice flip(1) ?  y - x :  x - y)` works fine.
The semantics of `ifelse` in julia are that the branches get evaluated first, regardless of the guard (making it branch-free). I think the behavior above is in line with those semantics.
